//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expro.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expro.Resources.ResourceTexts", typeof(ResourceTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обо мне.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить образование.
        /// </summary>
        public static string AddEducation {
            get {
                return ResourceManager.GetString("AddEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать новый вопрос.
        /// </summary>
        public static string AddNewQuestion {
            get {
                return ResourceManager.GetString("AddNewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать новый вопрос с вознаграждением.
        /// </summary>
        public static string AddNewQuestionWithFee {
            get {
                return ResourceManager.GetString("AddNewQuestionWithFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить опыть работы.
        /// </summary>
        public static string AddWorkexperience {
            get {
                return ResourceManager.GetString("AddWorkexperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все эксперты.
        /// </summary>
        public static string AllExperts {
            get {
                return ResourceManager.GetString("AllExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже покупали этот материал. Нажмите &lt;a href=&quot;/{0}/{1}Purchased/Details/{2}&quot;&gt;здесь&lt;/a&gt;, чтобы посмотреть..
        /// </summary>
        public static string AlreadyPurchased {
            get {
                return ResourceManager.GetString("AlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответ №.
        /// </summary>
        public static string AnswerN {
            get {
                return ResourceManager.GetString("AnswerN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответы.
        /// </summary>
        public static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст ответа.
        /// </summary>
        public static string AnswerText {
            get {
                return ResourceManager.GetString("AnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите закрыть вопрос, не распределив гонорар?.
        /// </summary>
        public static string AreYouSureToCloseQuestionWithoutFeeDistribution {
            get {
                return ResourceManager.GetString("AreYouSureToCloseQuestionWithoutFeeDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите купить.
        /// </summary>
        public static string AreYouSureYouWantToPurchase {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья не найдена.
        /// </summary>
        public static string ArticleNotFound {
            get {
                return ResourceManager.GetString("ArticleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статьи.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество статей.
        /// </summary>
        public static string ArticlesCount {
            get {
                return ResourceManager.GetString("ArticlesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать вопрос.
        /// </summary>
        public static string AskQuestion {
            get {
                return ResourceManager.GetString("AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/Identity/Account/Login?returnUrl=/User/Question&apos;&gt;Войдите&lt;/a&gt; или &lt;a href=&apos;/Identity/Account/Register?returnUrl=/User/Question&apos;&gt;зарегистрируйтесь&lt;/a&gt;, чтобы задать вопрос.
        /// </summary>
        public static string AskQuestionPopover {
            get {
                return ResourceManager.GetString("AskQuestionPopover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задайте вопрос экспертам.
        /// </summary>
        public static string AskQuestionTheExperts {
            get {
                return ResourceManager.GetString("AskQuestionTheExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;/Identity/Account/Login?returnUrl={0}&quot;&gt;Авторизуйтесь&lt;/a&gt;, чтобы купить..
        /// </summary>
        public static string AuthorizeToPurchase {
            get {
                return ResourceManager.GetString("AuthorizeToPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения сохранены.
        /// </summary>
        public static string ChangesSaved {
            get {
                return ResourceManager.GetString("ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть вопрос.
        /// </summary>
        public static string CloseQuestion {
            get {
                return ResourceManager.GetString("CloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст комментария.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компании.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог компаний.
        /// </summary>
        public static string CompaniesCatalog {
            get {
                return ResourceManager.GetString("CompaniesCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только подтвержденные.
        /// </summary>
        public static string ConfirmedOnly {
            get {
                return ResourceManager.GetString("ConfirmedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать страну.
        /// </summary>
        public static string CountrySelect {
            get {
                return ResourceManager.GetString("CountrySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные успешно сохранены.
        /// </summary>
        public static string DataSuccessfullySaved {
            get {
                return ResourceManager.GetString("DataSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата изменения.
        /// </summary>
        public static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата публикации.
        /// </summary>
        public static string DatePublished {
            get {
                return ResourceManager.GetString("DatePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диплом.
        /// </summary>
        public static string Diploma {
            get {
                return ResourceManager.GetString("Diploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распределить гонорар.
        /// </summary>
        public static string DistributeFee {
            get {
                return ResourceManager.GetString("DistributeFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментировать.
        /// </summary>
        public static string DoComment {
            get {
                return ResourceManager.GetString("DoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ бесплатный.
        /// </summary>
        public static string DocumentIsFree {
            get {
                return ResourceManager.GetString("DocumentIsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ не найден.
        /// </summary>
        public static string DocumentNotFound {
            get {
                return ResourceManager.GetString("DocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет аккаунта?.
        /// </summary>
        public static string DoNotHaveAccess {
            get {
                return ResourceManager.GetString("DoNotHaveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать вопрос.
        /// </summary>
        public static string EditQuestion {
            get {
                return ResourceManager.GetString("EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образование.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string ErrorRequiredField {
            get {
                return ResourceManager.GetString("ErrorRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эксперт.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эксперты.
        /// </summary>
        public static string Experts {
            get {
                return ResourceManager.GetString("Experts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество экспертов.
        /// </summary>
        public static string ExpertsCount {
            get {
                return ResourceManager.GetString("ExpertsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вознаграждение.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вознаграждение (в сумах).
        /// </summary>
        public static string FeeInSoums {
            get {
                return ResourceManager.GetString("FeeInSoums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вознаграждение успешно распределено.
        /// </summary>
        public static string FeeIsSuccessfullyDistributed {
            get {
                return ResourceManager.GetString("FeeIsSuccessfullyDistributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено вознаграждение.
        /// </summary>
        public static string FeePaid {
            get {
                return ResourceManager.GetString("FeePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть вложенный файл.
        /// </summary>
        public static string FileIsAttached {
            get {
                return ResourceManager.GetString("FileIsAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по направлению.
        /// </summary>
        public static string FilterByLawArea {
            get {
                return ResourceManager.GetString("FilterByLawArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по цене.
        /// </summary>
        public static string FilterByPrice {
            get {
                return ResourceManager.GetString("FilterByPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по статусу.
        /// </summary>
        public static string FilterByStatus {
            get {
                return ResourceManager.GetString("FilterByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узбекский.
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесплатные.
        /// </summary>
        public static string FreeItems {
            get {
                return ResourceManager.GetString("FreeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суммарно должно быть 100%.
        /// </summary>
        public static string ItMustBe100PercentInTotal {
            get {
                return ResourceManager.GetString("ItMustBe100PercentInTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другой город.
        /// </summary>
        public static string lblCityOther {
            get {
                return ResourceManager.GetString("lblCityOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введеные пароли не совпадают.
        /// </summary>
        public static string lblConfirmPasswordError {
            get {
                return ResourceManager.GetString("lblConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string lblDateOfBirth {
            get {
                return ResourceManager.GetString("lblDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайтда с.
        /// </summary>
        public static string lblDateRegistered {
            get {
                return ResourceManager.GetString("lblDateRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факультет.
        /// </summary>
        public static string lblFaculty {
            get {
                return ResourceManager.GetString("lblFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факс.
        /// </summary>
        public static string lblFax {
            get {
                return ResourceManager.GetString("lblFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год окончания.
        /// </summary>
        public static string lblGraduationYear {
            get {
                return ResourceManager.GetString("lblGraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление.
        /// </summary>
        public static string lblLawAreas {
            get {
                return ResourceManager.GetString("lblLawAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string lblPatronymicName {
            get {
                return ResourceManager.GetString("lblPatronymicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        public static string lblPhoneNumber {
            get {
                return ResourceManager.GetString("lblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место работы.
        /// </summary>
        public static string lblPlaceOfWork {
            get {
                return ResourceManager.GetString("lblPlaceOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        public static string lblRegion {
            get {
                return ResourceManager.GetString("lblRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВУЗ.
        /// </summary>
        public static string lblUniversity {
            get {
                return ResourceManager.GetString("lblUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веб сайт.
        /// </summary>
        public static string lblWebSite {
            get {
                return ResourceManager.GetString("lblWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период с.
        /// </summary>
        public static string lblWorkPeriodFrom {
            get {
                return ResourceManager.GetString("lblWorkPeriodFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период по.
        /// </summary>
        public static string lblWorkPeriodTo {
            get {
                return ResourceManager.GetString("lblWorkPeriodTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основная информация.
        /// </summary>
        public static string MainInfo {
            get {
                return ResourceManager.GetString("MainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои вопросы.
        /// </summary>
        public static string MyQuestions {
            get {
                return ResourceManager.GetString("MyQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответов нет.
        /// </summary>
        public static string NoAnswers {
            get {
                return ResourceManager.GetString("NoAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На вашем балансе недостаточно средств для покупки. Пожалуйста, пополните баланс..
        /// </summary>
        public static string NotEnoughMoneyOnBalancePleaseReplenish {
            get {
                return ResourceManager.GetString("NotEnoughMoneyOnBalancePleaseReplenish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно средств на балансе.
        /// </summary>
        public static string NotEnougthMoneyOnBalance {
            get {
                return ResourceManager.GetString("NotEnougthMoneyOnBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платные.
        /// </summary>
        public static string PaidItems {
            get {
                return ResourceManager.GetString("PaidItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период.
        /// </summary>
        public static string PeriodOfWork {
            get {
                return ResourceManager.GetString("PeriodOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персональная информация.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить фото.
        /// </summary>
        public static string PhotoUpload {
            get {
                return ResourceManager.GetString("PhotoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практический документ.
        /// </summary>
        public static string PracticeDocument {
            get {
                return ResourceManager.GetString("PracticeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практический документ не найден.
        /// </summary>
        public static string PracticeDocumentNotFound {
            get {
                return ResourceManager.GetString("PracticeDocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практические документы.
        /// </summary>
        public static string PracticeDocuments {
            get {
                return ResourceManager.GetString("PracticeDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать профайл.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос закрыт.
        /// </summary>
        public static string QuestionClosed {
            get {
                return ResourceManager.GetString("QuestionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос - детали.
        /// </summary>
        public static string QuestionDetails {
            get {
                return ResourceManager.GetString("QuestionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос не имеет вознаграждение.
        /// </summary>
        public static string QuestionHasNoFee {
            get {
                return ResourceManager.GetString("QuestionHasNoFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос подтвержден администратором.
        /// </summary>
        public static string QuestionIsApprovedByAdmin {
            get {
                return ResourceManager.GetString("QuestionIsApprovedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос отменен администратором.
        /// </summary>
        public static string QuestionIsRejectedByAdmin {
            get {
                return ResourceManager.GetString("QuestionIsRejectedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос отправлен на подтверждение.
        /// </summary>
        public static string QuestionIsSentForApproval {
            get {
                return ResourceManager.GetString("QuestionIsSentForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос не найден.
        /// </summary>
        public static string QuestionNotFound {
            get {
                return ResourceManager.GetString("QuestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть вопросы?.
        /// </summary>
        public static string Questions_ {
            get {
                return ResourceManager.GetString("Questions?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество вопросов.
        /// </summary>
        public static string QuestionsCount {
            get {
                return ResourceManager.GetString("QuestionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы, на которые я ответил.
        /// </summary>
        public static string QuestionsHavingMyAnswer {
            get {
                return ResourceManager.GetString("QuestionsHavingMyAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос решен.
        /// </summary>
        public static string QuestionSolved {
            get {
                return ResourceManager.GetString("QuestionSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RandomGUID это {0}.
        /// </summary>
        public static string RandomGUID {
            get {
                return ResourceManager.GetString("RandomGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться как пользователь.
        /// </summary>
        public static string RegisterAsASimpleUser {
            get {
                return ResourceManager.GetString("RegisterAsASimpleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться как эксперт.
        /// </summary>
        public static string RegistrateAsExpert {
            get {
                return ResourceManager.GetString("RegistrateAsExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить баланс на {0} сум (CLICK).
        /// </summary>
        public static string ReplenishBalanceOn {
            get {
                return ResourceManager.GetString("ReplenishBalanceOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резюме.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог резюме.
        /// </summary>
        public static string ResumeCatalog {
            get {
                return ResourceManager.GetString("ResumeCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образцовый документ.
        /// </summary>
        public static string SampleDocument {
            get {
                return ResourceManager.GetString("SampleDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образцовый документ не найден.
        /// </summary>
        public static string SampleDocumentNotFound {
            get {
                return ResourceManager.GetString("SampleDocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образцовые документы.
        /// </summary>
        public static string SampleDocuments {
            get {
                return ResourceManager.GetString("SampleDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество образцовых документов.
        /// </summary>
        public static string SampleDocumentsCount {
            get {
                return ResourceManager.GetString("SampleDocumentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как черновик.
        /// </summary>
        public static string SaveAsDraft {
            get {
                return ResourceManager.GetString("SaveAsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть все.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите хотя бы один ответ.
        /// </summary>
        public static string SelectAtLeastOneAnswer {
            get {
                return ResourceManager.GetString("SelectAtLeastOneAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать город.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать регион.
        /// </summary>
        public static string SelectRegion {
            get {
                return ResourceManager.GetString("SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то не так с выбранными ответами.
        /// </summary>
        public static string SomethingIsWrongWithSelectedAnswers {
            get {
                return ResourceManager.GetString("SomethingIsWrongWithSelectedAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сум.
        /// </summary>
        public static string soum {
            get {
                return ResourceManager.GetString("soum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус не позволяет подтвердить его.
        /// </summary>
        public static string StatusDoesNotAllowToApprove {
            get {
                return ResourceManager.GetString("StatusDoesNotAllowToApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус не позволяет отменить его.
        /// </summary>
        public static string StatusDoesNotAllowToReject {
            get {
                return ResourceManager.GetString("StatusDoesNotAllowToReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить на подтверждение.
        /// </summary>
        public static string SubmitForApproval {
            get {
                return ResourceManager.GetString("SubmitForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОП эксперты.
        /// </summary>
        public static string TopExperts {
            get {
                return ResourceManager.GetString("TopExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/Identity/Account/Login?returnUrl={0}&apos;&gt;Войдите&lt;/a&gt;, чтобы дислайкнуть.
        /// </summary>
        public static string UnauthorizedDislikePopover {
            get {
                return ResourceManager.GetString("UnauthorizedDislikePopover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/Identity/Account/Login?returnUrl={0}&apos;&gt;Войдите&lt;/a&gt;, чтобы лайкнуть.
        /// </summary>
        public static string UnauthorizedLikePopover {
            get {
                return ResourceManager.GetString("UnauthorizedLikePopover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить диплом.
        /// </summary>
        public static string UploadDiploma {
            get {
                return ResourceManager.GetString("UploadDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычный.
        /// </summary>
        public static string Usual {
            get {
                return ResourceManager.GetString("Usual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычные.
        /// </summary>
        public static string Usuals {
            get {
                return ResourceManager.GetString("Usuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансии.
        /// </summary>
        public static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог вакансий.
        /// </summary>
        public static string VacanciesCatalog {
            get {
                return ResourceManager.GetString("VacanciesCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать все фильтры.
        /// </summary>
        public static string ViewAllFilters {
            get {
                return ResourceManager.GetString("ViewAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы ответить на вопрос с вознаграждением, требуется набрать 100 баллов и подтвердить образование (диплом). Подробнее читайте &lt;a href=&quot;#&quot;&gt;условия оказания платных услуг&lt;/a&gt;.
        /// </summary>
        public static string WarningNotEnoughPointToGiveAnswerForQuestionWithFee {
            get {
                return ResourceManager.GetString("WarningNotEnoughPointToGiveAnswerForQuestionWithFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С вознаграждением.
        /// </summary>
        public static string WithFee {
            get {
                return ResourceManager.GetString("WithFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опыт работы.
        /// </summary>
        public static string Workexperience {
            get {
                return ResourceManager.GetString("Workexperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать ответ.
        /// </summary>
        public static string WriteAnswer {
            get {
                return ResourceManager.GetString("WriteAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не авторизованы.
        /// </summary>
        public static string YouAreNotAuthorized {
            get {
                return ResourceManager.GetString("YouAreNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш баланс.
        /// </summary>
        public static string YourBalance {
            get {
                return ResourceManager.GetString("YourBalance", resourceCulture);
            }
        }
    }
}
